services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gateway
      - minio
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - USER_SERVICE_URL=http://user-service:8002
      - FILE_SERVICE_URL=http://file-service:8003
      - PAYMENT_SERVICE_URL=http://payment-service:8004
    depends_on:
      - auth-service
      - user-service
      - file-service
      - payment-service

  auth-service:
    build: ./auth-service
    environment:
      - MONGODB_URL=mongodb://mongo:27017/auth_db
      - REDIS_URL=redis://redis:6379

  user-service:
    build: ./user-service
    environment:
      - MONGODB_URL=mongodb://mongo:27017/user_db

  file-service:
    build: ./file-service
    environment:
      - MONGODB_URL=mongodb://mongo:27017/file_db
      - MINIO_URL=http://minio:9000

  payment-service:
    build: ./payment-service
    environment:
      - MONGODB_URL=mongodb://mongo:27017/payment_db
      - WEB3_PROVIDER=https://mainnet.infura.io/v3/YOUR_INFURA_KEY

  notification-service:
    build: ./notification-service
    environment:
      - REDIS_URL=redis://redis:6379

  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  frontend:
    build: ./frontend

